db:  
  image: mongo
  ports:
    - "27017:27017"
synchronousfidelity:  
  build: .
  links:
    - db
  ports:
    - "8000:8000"
  environment:
    - PORT=8000
    - MONGODB_URI=mongodb://db:27017/synchrony
    - NODE_ENV=production
    - MONGODB_MAX_TIMEOUT=60000
